/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.ruppyrup.javapoet.plugin

import org.apache.commons.io.FileUtils
import org.gradle.testkit.runner.GradleRunner
import spock.lang.Specification
import spock.lang.TempDir

import java.nio.charset.Charset;


/**
 * A simple functional test for the 'tasktimer.greeting' plugin.
 */
class BuildersFunctionalTest extends Specification {
    @TempDir
    private File projectDir

    private getBuildFile() {
        new File(projectDir, "build.gradle")
    }

    private getSettingsFile() {
        new File(projectDir, "settings.gradle")
    }

    def "can create standard builders"() {
        given:
        settingsFile << ""
        buildFile << """
plugins {
    id 'java-library'
    id 'com.ruppyrup.javapoet.plugin.poetBuilder'
}


println System.getProperty("user.dir")


poetBuilder {
    schemaDir = 'src/functionalTest/resources/schemas'
    outputDir = "${projectDir.getPath()}"
    defaultKey = "sample"
    builderType = "standard"
}
"""

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("generateBuilders")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        assertGenertedClassMatchesExpected("standard","schema1", "Parent")
        assertGenertedClassMatchesExpected("standard", "schema1", "PostalCode")
        assertGenertedClassMatchesExpected("standard", "schema1", "Address")
        assertGenertedClassMatchesExpected("standard", "schema2", "Child")
        assertGenertedClassMatchesExpected("standard", "schema2", "PostalCode")
        assertGenertedClassMatchesExpected("standard", "schema2", "Address")
    }

    def "can create lombok builders"() {
        given:
        settingsFile << ""
        buildFile << """
plugins {
    id 'java-library'
    id "io.freefair.lombok" version "8.6"
    id 'com.ruppyrup.javapoet.plugin.poetBuilder'
}


println System.getProperty("user.dir")


poetBuilder {
    schemaDir = 'src/functionalTest/resources/schemas'
    outputDir = "${projectDir.getPath()}"
    defaultKey = "sample"
}
"""

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("generateBuilders")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        assertGenertedClassMatchesExpected("lombok","schema1", "Parent")
        assertGenertedClassMatchesExpected("lombok","schema1", "PostalCode")
        assertGenertedClassMatchesExpected("lombok","schema1", "Address")
//        assertGenertedClassMatchesExpected("schema2", "Child")
//        assertGenertedClassMatchesExpected("schema2", "PostalCode")
//        assertGenertedClassMatchesExpected("schema2", "Address")
    }

    private void assertGenertedClassMatchesExpected(String builderType, String path, String className) {
        def generated = projectDir.toPath().resolve("com/ruppyrup/javapoet/" + path + "/" + className + ".java").toFile()
        def generatedString = FileUtils.readFileToString(generated, Charset.defaultCharset())
        def expected = FileUtils.readFileToString(new File("src/functionalTest/resources/expected/" + builderType + "/" + path + "/" + className + "_Expected.txt"), Charset.defaultCharset())

        assert generatedString == expected
    }
}
